name: dart_parse
version: 0.0.1
author: Mantas Palaima <palaima.mantas@gmail.com>
description: A Dart client for the Parse REST API.
homepage: https://github.com/palaima/DartParse
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.11.0'
  matcher: '>=0.11.0'
  logging: '>=0.9.2 <0.10.0'
dependencies:
  http: any
  json_object: any
  mime_type: any
